spring:
  application:
    name: product
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.140.134/isell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.1.21
    port: 5672
    username: guest
    password: guest 
  redis:
    host: 192.168.1.21
    port: 6379      